# Generated by Django 6.1 on 2026-08-13 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_fa",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "category_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "category_fa",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "category_ar",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="article_covers/",
                        verbose_name="Cover Image",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("content_en", models.TextField(null=True, verbose_name="Content")),
                ("content_fa", models.TextField(null=True, verbose_name="Content")),
                ("content_ar", models.TextField(null=True, verbose_name="Content")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_fa",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "summary_fa",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "summary_ar",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "full_name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "full_name_fa",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "full_name_ar",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Full Name"
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("text_en", models.TextField(null=True, verbose_name="Text")),
                ("text_fa", models.TextField(null=True, verbose_name="Text")),
                ("text_ar", models.TextField(null=True, verbose_name="Text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
