# Generated by Django 6.1 on 2026-08-17 12:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_created_at_alter_article_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[("fa", "Persian"), ("en", "English"), ("ar", "Arabic")],
                default="fa",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_ar",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_fa",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=200,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="blog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category_ar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="blog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category_en",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="blog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category_fa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="blog.category",
                verbose_name="Category",
            ),
        ),
    ]
