# Generated by Django 6.1 on 2026-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_article_language_alter_article_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category_ar",
        ),
        migrations.RemoveField(
            model_name="article",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="category_fa",
        ),
        migrations.RemoveField(
            model_name="article",
            name="content_ar",
        ),
        migrations.RemoveField(
            model_name="article",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="content_fa",
        ),
        migrations.RemoveField(
            model_name="article",
            name="description_ar",
        ),
        migrations.RemoveField(
            model_name="article",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="description_fa",
        ),
        migrations.RemoveField(
            model_name="article",
            name="summary_ar",
        ),
        migrations.RemoveField(
            model_name="article",
            name="summary_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="summary_fa",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_fa",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="full_name_ar",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="full_name_en",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="full_name_fa",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="text_ar",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="text_en",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="text_fa",
        ),
        migrations.AddField(
            model_name="category",
            name="title_ar",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="category",
            name="title_fa",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
    ]
