# Generated by Django 6.1 on 2026-08-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderrequest",
            old_name="description",
            new_name="massage",
        ),
    ]
