# Generated by Django 6.1 on 2026-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_rename_description_orderrequest_massage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactwithus",
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="orderrequest",
            options={
                "verbose_name": "Order Request",
                "verbose_name_plural": "Order Requests",
            },
        ),
        migrations.RenameField(
            model_name="orderrequest",
            old_name="massage",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="contactwithus",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="orderrequest",
            name="is_reviewed",
        ),
        migrations.AddField(
            model_name="contactwithus",
            name="status",
            field=models.CharField(
                choices=[("unread", "خوانده نشده"), ("read", "خوانده شده")],
                default="unread",
                max_length=20,
                verbose_name="Read Status",
            ),
        ),
        migrations.AddField(
            model_name="contactwithus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در حال بررسی"),
                    ("reviewed", "بررسی شده"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Review Status",
            ),
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="contactwithus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
            ),
        ),
    ]
