# Generated by Django 6.1 on 2026-08-17 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_orderrequest_video_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequest",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,15}$")
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
