# Generated by Django 6.1 on 2026-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("achievement", models.TextField(verbose_name="Achievement")),
                ("date", models.DateField(verbose_name="Date")),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "Histories",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="Name")),
                ("position", models.CharField(max_length=100, verbose_name="Role")),
                ("bio", models.TextField(verbose_name="Bio")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team_profiles/",
                        verbose_name="Profile Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["full_name"],
            },
        ),
    ]
