# Generated by Django 6.1 on 2026-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="achievement_ar",
            field=models.TextField(null=True, verbose_name="Achievement"),
        ),
        migrations.AddField(
            model_name="history",
            name="achievement_en",
            field=models.TextField(null=True, verbose_name="Achievement"),
        ),
        migrations.AddField(
            model_name="history",
            name="achievement_fa",
            field=models.TextField(null=True, verbose_name="Achievement"),
        ),
        migrations.AddField(
            model_name="history",
            name="title_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="history",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="history",
            name="title_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_ar",
            field=models.TextField(null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_en",
            field=models.TextField(null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_fa",
            field=models.TextField(null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="full_name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="full_name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="full_name_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="position_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="Role"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="position_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Role"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="position_fa",
            field=models.CharField(max_length=100, null=True, verbose_name="Role"),
        ),
    ]
