# Generated by Django 6.1 on 2026-08-16 13:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_history_achievement_ar_history_achievement_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"verbose_name": "History", "verbose_name_plural": "Histories"},
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AddField(
            model_name="history",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2026, 8, 16, 13, 2, 44, 818232, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
    ]
