# Generated by Django 6.1 on 2026-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_history_options_alter_teammember_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
