# Generated by Django 6.1 on 2026-08-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_history_created_at_alter_history_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "History",
                "verbose_name_plural": "Histories",
            },
        ),
        migrations.AlterField(
            model_name="history",
            name="date",
            field=models.CharField(max_length=50, verbose_name="Year"),
        ),
    ]
