# Generated by Django 6.1 on 2026-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_alter_history_options_alter_history_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio_en",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio_fa",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
    ]
