# Generated by Django 6.1 on 2026-08-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_alter_teammember_bio_alter_teammember_bio_ar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={
                "ordering": ["-year"],
                "verbose_name": "History",
                "verbose_name_plural": "Histories",
            },
        ),
        migrations.RenameField(
            model_name="history",
            old_name="date",
            new_name="year",
        ),
    ]
