# Generated by Django 6.1 on 2026-08-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_alter_history_options_rename_date_history_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"verbose_name": "History", "verbose_name_plural": "Histories"},
        ),
        migrations.AddField(
            model_name="history",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
    ]
