# Generated by Django 6.1 on 2026-08-16 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="category",
            name="active_status",
            field=models.CharField(
                choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                default="active",
                max_length=20,
                verbose_name="Active Status",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="is_active",
            field=models.CharField(
                choices=[("active", "فعال"), ("inactive", "غیرفعال")],
                default="active",
                max_length=20,
                verbose_name="Active",
            ),
        ),
    ]
