# Generated by Django 6.1 on 2026-08-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_category_created_at_alter_category_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["order"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Gallery",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="Slug (URL)",
            ),
        ),
    ]
