# Generated by Django 6.1 on 2026-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_project_options_alter_projectimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
